<a href="https://colab.research.google.com/github/RaphaelPetit/NCAA-BasketBall-Forecasting/blob/main/DataSection3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path6 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/OriouVF.csv'
df6 = pd.read_csv(path6)

df6 = df6.drop(columns=['Unnamed: 0'])

In [ ]:
path7 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/MGameCities.csv'
game_cities = pd.read_csv(path7)

In [ ]:
game_cities

       Season  DayNum  WTeamID  LTeamID   CRType  CityID
0        2010       7     1143     1293  Regular    4027
1        2010       7     1314     1198  Regular    4061
2        2010       7     1326     1108  Regular    4080
3        2010       7     1393     1107  Regular    4340
4        2010       9     1143     1178  Regular    4027
...       ...     ...      ...      ...      ...     ...
86230    2025     120     1433     1182  Regular    4270
86231    2025     120     1436     1107  Regular    4051
86232    2025     120     1438     1199  Regular    4067
86233    2025     120     1452     1428  Regular    4301
86234    2025     120     1460     1237  Regular    4091

[86235 rows x 6 columns]

In [ ]:
path8 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/Cities.csv'
cities = pd.read_csv(path8)

In [ ]:
cities

     CityID          City State
0      4001       Abilene    TX
1      4002         Akron    OH
2      4003        Albany    NY
3      4004   Albuquerque    NM
4      4005     Allentown    PA
..      ...           ...   ...
497    4520     Stateline    NV
498    4521      Westwego    LA
499    4522     Frankfort    KY
500    4523      Rockford    IL
501    4524  Collierville    TN

[502 rows x 3 columns]

In [ ]:
df6 = df6.merge(game_cities[['Season', 'DayNum', 'WTeamID', 'LTeamID', 'CityID']],
                left_on=['Season', 'T1_TeamID', 'T2_TeamID'],
                right_on=['Season', 'WTeamID', 'LTeamID'],
                how='left')

In [ ]:

df6.drop(columns=['WTeamID', 'LTeamID'], inplace=True)

In [ ]:
df6

,Season,DayNum_x,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_Scoremean_mn3s,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality,DayNum_y,CityID
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,72.800000,55.266667,18.500000,16,16,True,0.200000,0.200000,NaN,NaN
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,67.793103,55.862069,15.482759,1,16,True,0.200000,0.200000,NaN,NaN
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,74.517241,60.000000,20.068966,10,7,True,0.200000,0.200000,NaN,NaN
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,79.242424,57.454545,20.484848,11,6,True,0.200000,0.200000,NaN,NaN
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,72.400000,53.333333,22.500000,8,9,True,0.200000,0.200000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2792,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,76.407828,62.281408,22.303188,4,11,False,2.788566,2.764296,119.0,4287.0
2793,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,79.358734,57.196970,20.967023,2,1,False,2.746453,2.873807,NaN,NaN
2794,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,79.418059,59.594047,23.899751,4,1,False,2.669547,2.913213,NaN,NaN
2795,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,79.358734,57.196970,20.967023,11,1,False,2.764296,2.873807,NaN,NaN
2796,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,79.418059,59.594047,23.899751,1,1,False,2.873807,2.913213,NaN,NaN

In [ ]:
city_pop = game_cities['CityID'].value_counts().reset_index()
city_pop.columns = ['CityID', 'Game_Popularity']

In [ ]:
df6 = df6.merge(city_pop, on='CityID', how='left')

In [ ]:
df6.drop(columns=['DayNum_y'], inplace=True)

In [ ]:
df6

,Season,DayNum_x,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_Scoremean_mn3s,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality,CityID,Game_Popularity
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,72.800000,55.266667,18.500000,16,16,True,0.200000,0.200000,NaN,NaN
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,67.793103,55.862069,15.482759,1,16,True,0.200000,0.200000,NaN,NaN
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,74.517241,60.000000,20.068966,10,7,True,0.200000,0.200000,NaN,NaN
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,79.242424,57.454545,20.484848,11,6,True,0.200000,0.200000,NaN,NaN
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,72.400000,53.333333,22.500000,8,9,True,0.200000,0.200000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2792,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,76.407828,62.281408,22.303188,4,11,False,2.788566,2.764296,4287.0,295.0
2793,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,79.358734,57.196970,20.967023,2,1,False,2.746453,2.873807,NaN,NaN
2794,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,79.418059,59.594047,23.899751,4,1,False,2.669547,2.913213,NaN,NaN
2795,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,79.358734,57.196970,20.967023,11,1,False,2.764296,2.873807,NaN,NaN
2796,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,79.418059,59.594047,23.899751,1,1,False,2.873807,2.913213,NaN,NaN

In [ ]:
label = 'T1Won'

def evaluate_model(mod, data, features):
  model = mod
  data_train = data[data['Season'] != 2024]
  data_test = data[data['Season'] == 2024]
  X_train = data_train[features]
  y_train = data_train[label]
  X_test = data_test[features]
  y_test = data_test[label]
  model.fit(X_train, y_train)
  pred = model.predict(X_test)
  pred_proba = model.predict_proba(X_test)[:,1]
  acc = (pred == y_test).mean()
  brier = ((pred_proba - y_test)**2).mean()
  return f"accuracy : {acc} , brier score : {brier}"

In [ ]:
from sklearn.ensemble import RandomForestClassifier

features = ['T2_seed', 'T1_seed', 'T1_PointDiffmean', 'T2_PointDiffmean',
       'T2_Scoremean_mn3s', 'T1_FGMmean', 'T1_Scoremean_mn3s',
       'T2_FGMmean', 'T1_PFmean', 'T2_opponent_Scoremean',
       'T1_opponent_Scoremean', 'T2_Scoremean', 'T1_Scoremean',
       'T2_TOmean', 'T1_TOmean', 'T2_PFmean', 'T1_Astmean',
       'T1_opponent_ORmean', 'T2_TOQUETOQUEmean', 'T1_opponent_Stlmean',
       'T2_FGAmean_mn3s', 'T2_FGAmean', 'T1_opponent_FGMmean',
       'T1_FGAmean_mn3s', 'T2_Stlmean', 'T1_ORmean', 'T2_Astmean',
       'T2_opponent_Blkmean', 'T2_opponent_Stlmean',
       'T1_opponent_EFFGmean', 'T1_quality', 'T2_quality', 'CityID', 'Game_Popularity']

RF1 = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)
evaluate_model(RF1,df6,features)

'accuracy : 0.9855072463768116 , brier score : 0.01932826086956522'

In [ ]:
#mdr

In [ ]:
df6[['CityID', 'Game_Popularity']].isna().sum()

CityID             1812
Game_Popularity    1812
dtype: int64