<a href="https://colab.research.google.com/github/RaphaelPetit/NCAA-BasketBall-Forecasting/blob/main/DataSection5_2%263.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path6 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/OriouVF.csv'
df6 = pd.read_csv(path6)

df6 = df6.drop(columns=['Unnamed: 0'])

In [ ]:
df6

,Season,DayNum,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_opponent_DAREmean,T2_opponent_TOQUETOQUEmean,T2_Scoremean_mn3s,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,0.260372,0.502632,72.800000,55.266667,18.500000,16,16,True,0.200000,0.200000
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,0.319844,0.544214,67.793103,55.862069,15.482759,1,16,True,0.200000,0.200000
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,0.264035,0.580375,74.517241,60.000000,20.068966,10,7,True,0.200000,0.200000
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,0.205701,0.512530,79.242424,57.454545,20.484848,11,6,True,0.200000,0.200000
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,0.262301,0.525119,72.400000,53.333333,22.500000,8,9,True,0.200000,0.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,0.275590,0.475792,76.407828,62.281408,22.303188,4,11,False,2.788566,2.764296
2760,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,0.270790,0.532390,79.358734,57.196970,20.967023,2,1,False,2.746453,2.873807
2761,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,0.260506,0.445059,79.418059,59.594047,23.899751,4,1,False,2.669547,2.913213
2762,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,0.270790,0.532390,79.358734,57.196970,20.967023,11,1,False,2.764296,2.873807
2763,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,0.260506,0.445059,79.418059,59.594047,23.899751,1,1,False,2.873807,2.913213

# Feature Same_Conference

In [ ]:
path10 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/MTeamConferences.csv'
team_conf = pd.read_csv(path10)

In [ ]:
team_conf

       Season  TeamID ConfAbbrev
0        1985    1102        wac
1        1985    1103        ovc
2        1985    1104        sec
3        1985    1106       swac
4        1985    1108       swac
...       ...     ...        ...
13383    2025    1476        nec
13384    2025    1477  southland
13385    2025    1478        nec
13386    2025    1479        nec
13387    2025    1480      a_sun

[13388 rows x 3 columns]

In [ ]:
df6 = df6.merge(team_conf, left_on=['Season', 'T1_TeamID'], right_on=['Season', 'TeamID'], how='left')
df6.rename(columns={'ConfAbbrev' : 'ConfAbbrev_Team1'}, inplace=True)
df6.drop(columns=['TeamID'], inplace=True)

df6 = df6.merge(team_conf, left_on=['Season', 'T2_TeamID'], right_on=['Season', 'TeamID'], how='left')
df6.rename(columns={'ConfAbbrev' : 'ConfAbbrev_Team2'}, inplace=True)
df6.drop(columns=['TeamID'], inplace=True)

In [ ]:
# Créer la feature `Same_Conference` (1 si même conférence, sinon 0)
df6['Same_Conference'] = (df6['ConfAbbrev_Team1'] == df6['ConfAbbrev_Team2']).astype(int)

In [ ]:
df6

,Season,DayNum,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality,ConfAbbrev_Team1,ConfAbbrev_Team2,Same_Conference
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,55.266667,18.500000,16,16,True,0.200000,0.200000,big_south,swac,0
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,55.862069,15.482759,1,16,True,0.200000,0.200000,pac_ten,aec,0
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,60.000000,20.068966,10,7,True,0.200000,0.200000,pac_ten,cusa,0
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,57.454545,20.484848,11,6,True,0.200000,0.200000,mac,mvc,0
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,53.333333,22.500000,8,9,True,0.200000,0.200000,pac_ten,acc,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,62.281408,22.303188,4,11,False,2.788566,2.764296,acc,acc,1
2760,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,57.196970,20.967023,2,1,False,2.746453,2.873807,sec,big_ten,0
2761,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,59.594047,23.899751,4,1,False,2.669547,2.913213,sec,big_east,0
2762,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,57.196970,20.967023,11,1,False,2.764296,2.873807,acc,big_ten,0
2763,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,59.594047,23.899751,1,1,False,2.873807,2.913213,big_ten,big_east,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df6['ConfAbbrev_Team1'] = encoder.fit_transform(df6['ConfAbbrev_Team1'])
df6['ConfAbbrev_Team2'] = encoder.fit_transform(df6['ConfAbbrev_Team2'])

In [ ]:
df6

,Season,DayNum,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality,ConfAbbrev_Team1,ConfAbbrev_Team2,Same_Conference
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,55.266667,18.500000,16,16,True,0.200000,0.200000,7,31,0
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,55.862069,15.482759,1,16,True,0.200000,0.200000,23,4,0
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,60.000000,20.068966,10,7,True,0.200000,0.200000,23,12,0
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,57.454545,20.484848,11,6,True,0.200000,0.200000,16,19,0
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,53.333333,22.500000,8,9,True,0.200000,0.200000,23,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,62.281408,22.303188,4,11,False,2.788566,2.764296,3,3,1
2760,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,57.196970,20.967023,2,1,False,2.746453,2.873807,26,8,0
2761,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,59.594047,23.899751,4,1,False,2.669547,2.913213,26,5,0
2762,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,57.196970,20.967023,11,1,False,2.764296,2.873807,3,8,0
2763,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,59.594047,23.899751,1,1,False,2.873807,2.913213,8,5,0

# Evaluate the model

In [ ]:
label = 'T1Won'

def evaluate_model(mod, data, features):
  model = mod
  data_train = data[data['Season'] != 2024]
  data_test = data[data['Season'] == 2024]
  X_train = data_train[features]
  y_train = data_train[label]
  X_test = data_test[features]
  y_test = data_test[label]
  model.fit(X_train, y_train)
  pred = model.predict(X_test)
  pred_proba = model.predict_proba(X_test)[:,1]
  acc = (pred == y_test).mean()
  brier = ((pred_proba - y_test)**2).mean()
  return f"accuracy : {acc} , brier score : {brier}"

In [ ]:
from sklearn.ensemble import RandomForestClassifier

features = ['T2_seed', 'T1_seed', 'T1_PointDiffmean', 'T2_PointDiffmean',
       'T2_Scoremean_mn3s', 'T1_FGMmean', 'T1_Scoremean_mn3s',
       'T2_FGMmean', 'T1_PFmean', 'T2_opponent_Scoremean',
       'T1_opponent_Scoremean', 'T2_Scoremean', 'T1_Scoremean',
       'T2_TOmean', 'T1_TOmean', 'T2_PFmean', 'T1_Astmean',
       'T1_opponent_ORmean', 'T2_TOQUETOQUEmean', 'T1_opponent_Stlmean',
       'T2_FGAmean_mn3s', 'T2_FGAmean', 'T1_opponent_FGMmean',
       'T1_FGAmean_mn3s', 'T2_Stlmean', 'T1_ORmean', 'T2_Astmean',
       'T2_opponent_Blkmean', 'T2_opponent_Stlmean',
       'T1_opponent_EFFGmean', 'T1_quality', 'T2_quality', 'ConfAbbrev_Team1', 'ConfAbbrev_Team2', 'Same_Conference']

RF1 = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)
evaluate_model(RF1,df6,features)

'accuracy : 0.7164179104477612 , brier score : 0.18866119402985074'

In [ ]:
df6.drop(columns=['ConfAbbrev_Team1', 'ConfAbbrev_Team2', 'Same_Conference'], inplace=True)

# Feature Played_Conf_Tourney

In [ ]:
path11 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/MConferenceTourneyGames.csv'
conf_tourney = pd.read_csv(path11)

In [ ]:
conf_tourney

      Season ConfAbbrev  DayNum  WTeamID  LTeamID
0       2001      a_sun     121     1194     1144
1       2001      a_sun     121     1416     1240
2       2001      a_sun     122     1209     1194
3       2001      a_sun     122     1359     1239
4       2001      a_sun     122     1391     1273
...      ...        ...     ...      ...      ...
6499    2025    horizon     120     1460     1237
6500    2025    patriot     120     1248     1221
6501    2025    patriot     120     1259     1250
6502    2025   sun_belt     120     1379     1157
6503    2025   sun_belt     120     1418     1419

[6504 rows x 5 columns]

In [ ]:
#Played_Conf_Tourney : 1 si l'équipe à joué dans un tournoi de conference, 0 sinon
#interessant car les équipes ayant joué un tournoi de conférence ont une préparation plus intense


# on commence par créer une liste des équipes ayant joué en tournoi de conférence

# teams_in_conf_tourney = set(conf_tourney['WTeamID']).union(set(conf_tourney['LTeamID']))

# df6['Played_Conf_Tourney_Team1'] = df6['T1_ID'].isin(teams_in_conf_tourney).astype(int)
# df6['Played_Conf_Tourney_Team2'] = df6['T2_ID'].isin(teams_in_conf_tourney).astype(int)

#Aucun intérêt comme feature pcq tous les matchs font intervenir une équipe qui a joué en tournoi de conférence

In [ ]:
df6.drop(columns=['Played_Conf_Tourney_Team1', 'Played_Conf_Tourney_Team2'], inplace=True)

KeyError: "['Played_Conf_Tourney_Team1', 'Played_Conf_Tourney_Team2'] not found in axis"

In [ ]:
df6

,Season,DayNum,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_opponent_DAREmean,T2_opponent_TOQUETOQUEmean,T2_Scoremean_mn3s,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,0.260372,0.502632,72.800000,55.266667,18.500000,16,16,True,0.200000,0.200000
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,0.319844,0.544214,67.793103,55.862069,15.482759,1,16,True,0.200000,0.200000
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,0.264035,0.580375,74.517241,60.000000,20.068966,10,7,True,0.200000,0.200000
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,0.205701,0.512530,79.242424,57.454545,20.484848,11,6,True,0.200000,0.200000
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,0.262301,0.525119,72.400000,53.333333,22.500000,8,9,True,0.200000,0.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,0.275590,0.475792,76.407828,62.281408,22.303188,4,11,False,2.788566,2.764296
2760,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,0.270790,0.532390,79.358734,57.196970,20.967023,2,1,False,2.746453,2.873807
2761,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,0.260506,0.445059,79.418059,59.594047,23.899751,4,1,False,2.669547,2.913213
2762,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,0.270790,0.532390,79.358734,57.196970,20.967023,11,1,False,2.764296,2.873807
2763,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,0.260506,0.445059,79.418059,59.594047,23.899751,1,1,False,2.873807,2.913213

In [ ]:
df6[['ConfAbbrev_Team1', 'ConfAbbrev_Team2']].nunique() #3 conf qui n'ont pas qualif d'équipes en tournoi NCAA

ConfAbbrev_Team1    48
ConfAbbrev_Team2    48
dtype: int64

# Evaluate the model

In [ ]:
from sklearn.ensemble import RandomForestClassifier

features = ['T2_seed', 'T1_seed', 'T1_PointDiffmean', 'T2_PointDiffmean',
       'T2_Scoremean_mn3s', 'T1_FGMmean', 'T1_Scoremean_mn3s',
       'T2_FGMmean', 'T1_PFmean', 'T2_opponent_Scoremean',
       'T1_opponent_Scoremean', 'T2_Scoremean', 'T1_Scoremean',
       'T2_TOmean', 'T1_TOmean', 'T2_PFmean', 'T1_Astmean',
       'T1_opponent_ORmean', 'T2_TOQUETOQUEmean', 'T1_opponent_Stlmean',
       'T2_FGAmean_mn3s', 'T2_FGAmean', 'T1_opponent_FGMmean',
       'T1_FGAmean_mn3s', 'T2_Stlmean', 'T1_ORmean', 'T2_Astmean',
       'T2_opponent_Blkmean', 'T2_opponent_Stlmean',
       'T1_opponent_EFFGmean', 'T1_quality', 'T2_quality']

RF1 = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)
evaluate_model(RF1,df6,features)

'accuracy : 0.7611940298507462 , brier score : 0.18626492537313433'

# Feature Played_Secondary_Tourney

In [ ]:
path12 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/MSecondaryTourneyTeams.csv'
secondary_tourney = pd.read_csv(path12)

In [ ]:
secondary_tourney

      Season SecondaryTourney  TeamID
0       1985              NIT    1108
1       1985              NIT    1133
2       1985              NIT    1139
3       1985              NIT    1145
4       1985              NIT    1151
...      ...              ...     ...
1831    2024              NIT    1433
1832    2024              NIT    1437
1833    2024              NIT    1439
1834    2024              NIT    1448
1835    2024              NIT    1462

[1836 rows x 3 columns]

In [ ]:
teams_secondary_tourney = set(secondary_tourney['TeamID'])

In [ ]:
df6['Played_Secondary_Tourney_Team1'] = df6['T1_TeamID'].isin(teams_secondary_tourney).astype(int)
df6['Played_Secondary_Tourney_Team2'] = df6['T2_TeamID'].isin(teams_secondary_tourney).astype(int)

In [ ]:
df6['Played_Secondary_Tourney_Team1'].sum() #On a 4729 matchs qui font intervenir des équipes 1 ayant joué en div2 (idem pour Team2)

2609

In [ ]:
df6[['Played_Secondary_Tourney_Team1', 'Played_Secondary_Tourney_Team2']].value_counts()
#Pas super pertinent

Played_Secondary_Tourney_Team1  Played_Secondary_Tourney_Team2
1                               1                                 2464
0                               1                                  145
1                               0                                  145
0                               0                                   10
Name: count, dtype: int64

In [ ]:
df6

,Season,DayNum,T1_TeamID,T1_Score,T2_TeamID,T2_Score,T1_Scoremean,T1_opponent_Scoremean,T1_FGMmean,T1_FGAmean,...,T2_Scoremean_mn3s,T2_FGAmean_mn3s,T2_FGA3mean_mn3s,T1_seed,T2_seed,T1Won,T1_quality,T2_quality,Played_Secondary_Tourney_Team1,Played_Secondary_Tourney_Team2
0,2003,134,1421,92,1411,84,71.206897,78.448276,24.379310,56.793103,...,72.800000,55.266667,18.500000,16,16,True,0.200000,0.200000,1,1
1,2003,136,1112,80,1436,51,85.214286,70.250000,30.321429,65.714286,...,67.793103,55.862069,15.482759,1,16,True,0.200000,0.200000,1,1
2,2003,136,1113,84,1272,71,75.965517,69.172414,27.206897,56.896552,...,74.517241,60.000000,20.068966,10,7,True,0.200000,0.200000,1,1
3,2003,136,1141,79,1166,73,79.344828,73.241379,26.620690,52.689655,...,79.242424,57.454545,20.484848,11,6,True,0.200000,0.200000,1,1
4,2003,136,1143,76,1301,74,74.482759,69.758621,27.344828,58.724138,...,72.400000,53.333333,22.500000,8,9,True,0.200000,0.200000,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2759,2024,146,1181,64,1301,76,79.843750,67.437500,28.531250,59.218750,...,76.407828,62.281408,22.303188,4,11,False,2.788566,2.764296,0,1
2760,2024,146,1397,66,1345,72,79.468750,67.875000,27.437500,61.750000,...,79.358734,57.196970,20.967023,2,1,False,2.746453,2.873807,1,1
2761,2024,152,1104,72,1163,86,90.750000,81.062500,30.906250,64.750000,...,79.418059,59.594047,23.899751,4,1,False,2.669547,2.913213,1,1
2762,2024,152,1301,50,1345,63,76.361111,72.694444,27.388889,60.972222,...,79.358734,57.196970,20.967023,11,1,False,2.764296,2.873807,1,1
2763,2024,154,1345,60,1163,75,83.393939,70.151515,28.515152,58.393939,...,79.418059,59.594047,23.899751,1,1,False,2.873807,2.913213,1,1

In [ ]:
from sklearn.ensemble import RandomForestClassifier

features = ['T2_seed', 'T1_seed', 'T1_PointDiffmean', 'T2_PointDiffmean',
       'T2_Scoremean_mn3s', 'T1_FGMmean', 'T1_Scoremean_mn3s',
       'T2_FGMmean', 'T1_PFmean', 'T2_opponent_Scoremean',
       'T1_opponent_Scoremean', 'T2_Scoremean', 'T1_Scoremean',
       'T2_TOmean', 'T1_TOmean', 'T2_PFmean', 'T1_Astmean',
       'T1_opponent_ORmean', 'T2_TOQUETOQUEmean', 'T1_opponent_Stlmean',
       'T2_FGAmean_mn3s', 'T2_FGAmean', 'T1_opponent_FGMmean',
       'T1_FGAmean_mn3s', 'T2_Stlmean', 'T1_ORmean', 'T2_Astmean',
       'T2_opponent_Blkmean', 'T2_opponent_Stlmean',
       'T1_opponent_EFFGmean', 'T1_quality', 'T2_quality', 'Played_Secondary_Tourney_Team1', 'Played_Secondary_Tourney_Team2']

RF1 = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)
evaluate_model(RF1,df6,features)

'accuracy : 0.7238805970149254 , brier score : 0.19258656716417913'

In [ ]:
df6.drop(columns=['Played_Secondary_Tourney_Team1', 'Played_Secondary_Tourney_Team2'], inplace=True)

# Feature XXX

In [ ]:
path13 = '/content/drive/MyDrive/Challenges Data/march-machine-learning-mania-2025/MSecondaryTourneyCompactResults.csv'
res_second = pd.read_csv(path13)

In [ ]:
res_second[res_second['WTeamID'] == 1151]

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,SecondaryTourney
0,1985,136,1151,67,1155,65,H,0,NIT
16,1985,141,1151,85,1249,84,A,1,NIT

In [ ]:
res_second[['SecondaryTourney']].value_counts()

SecondaryTourney
NIT                 1250
CIT                  279
CBI                  253
TBC                   17
V16                    7
NIT                    3
Name: count, dtype: int64